name: Market Tracker CSV

on:
  schedule:
    - cron: "*/8 10-17 * * 1-5"  # a cada 15 minutos
  workflow_dispatch:       # permite rodar manualmente

permissions:
  contents: write  

jobs:
  update-csv:
    runs-on: ubuntu-latest
    env:
      DB_HOST: ${{ secrets.DB_HOST }}
      DB_USER: ${{ secrets.DB_USER }}
      DB_PASS: ${{ secrets.DB_PASS }}
      DB_NAME: ${{ secrets.DB_NAME }}
    steps:
      - name: Checkout repo
        uses: actions/checkout@v3

      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: '3.11'

      - name: Install dependencies
        run: pip install pandas mysql-connector-python

      - name: Run script
        run: python scripts/generate_csv.py

      - name: Commit CSV
        run: |
          git config --global user.name "github-actions[bot]"
          git config --global user.email "github-actions[bot]@users.noreply.github.com"
          git add data/market-tracker.csv
          git commit -m "Atualiza market-tracker.csv" || echo "Sem alterações"
          git push
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}

